allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@sayagodev/beidou@1.0.0'
  - '@sayagodev/beidou@1.1.0'
  - '@sayagodev/beidou@1.1.1'
