#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const packageJson = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8')
);
const version = packageJson.version;

const versionFile = `// This file is generated automatically. Do not edit manually.
// Generated by scripts/update-version.js

export const VERSION = '${version}';
export default VERSION;
`;

fs.writeFileSync(
  path.join(__dirname, '../src/version.ts'),
  versionFile,
  'utf8'
);

console.log(`✅ Version ${version} updated in src/version.ts`);
