#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const packageJson = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8')
);
const version = packageJson.version;

const versionFile = `// This file is generated automatically. Do not edit manually.
// Generated by scripts/update-version.js

export const VERSION = '${version}';
export default VERSION;
`;

const versionFilePath = path.join(__dirname, '../src/version.ts');
fs.writeFileSync(versionFilePath, versionFile, 'utf8');

// Agregar el archivo al staging area para que se incluya en el commit del release
try {
  execSync(`git add ${versionFilePath}`, { stdio: 'ignore' });
  console.error(`✅ Version ${version} updated in src/version.ts and staged`);
} catch (error) {
  console.error(`⚠️ Version ${version} updated in src/version.ts (git add failed, but file is updated)`);
  process.exit(1);
}
